### ISSUE TITLE
关于COMA critic网络输入

### ISSUE THREAD

**Issue by hjh0119** [starry-sky6688/MARL-Algorithms#101]
请问为什么critic网络需要输入上一时刻的联合动作u(t-1)? 原论文中好像也没有解释

**Comment by starry-sky6688** [comment]
看一下原文里的网络结构图，图里critic的输入是有的

**Comment by hjh0119** [comment]
原文中好像就只有网络结构图, 没有解释。
我比较困惑的是critic网络为什么需要输入上一时刻的联合动作以及当前时刻智能体的观测。
我的理解是图中的critic网络因为需要计算反事实基线中累加项中的π^a内置了actor网络，所以需要智能体的观测和之前的动作作为输入。
如果理解没错的话，代码里critic网络是否就不需要这部分的输入?

**Comment by starry-sky6688** [comment]
可以不需要；上一时刻的动作其实可以认为是观察的一部分
