### ISSUE TITLE
自定义的环境能使用这里面的算法跑吗？

### ISSUE THREAD

**Issue by shswdmx1** [starry-sky6688/MARL-Algorithms#104]
参考pettingzoo自定义的环境能使用这里面的算法跑吗？如果能的话，我需要看哪些文件呢？

**Comment by starry-sky6688** [comment]
不能直接跑，接其他环境需要修改环境的接口，使它和我们的算法库能匹配上

可以参考这个问题：https://github.com/starry-sky6688/MARL-Algorithms/issues/103
