### ISSUE TITLE
关于qtran的问题

### ISSUE THREAD

**Issue by Johnson221b** [starry-sky6688/MARL-Algorithms#109]
作者您好！
我最近在尝试利用您编写的qmix、qtran_base和qtran_alt算法解决无人机路径规划问题。在我做实验的过程中，从实际的表现上来看，qmix算法的性能要高于qtran_base（可能是我的参数设定出现了一些问题）。所以我想请问一下您在实验中qtran算法的实际性能表现是否比qmix要好呢，如果好的话大概好多少

此外，qtran_alt是不是比qtran_base难收敛很多，我尝试了很多次都没办法将qtran_alt收敛。是不有什么技巧或方法可以将qtran_alt收敛

最后对于rnn_hidden、qtran_hidden这两个qtran算法中的参数的设定设定您有没有什么规律或者调参经验可以分享一下的呢
非常感谢！！！

**Comment by starry-sky6688** [comment]
不同的算法在不同环境下性能也不一样，并不一定某个算法就一定是最好的，找到最合适的就行；

调参经验或者技巧和任务都是相关的，得你自己慢慢摸索
