### ISSUE TITLE
关于GA-Common和GA-AC的问题

### ISSUE THREAD

**Issue by issta24** [starry-sky6688/MARL-Algorithms#112]
作者您好！请问在G2ANet的原文中提到了GA-Common（通信模型中的策略网络）和GA-AC（行为评论家模型中的评论家网络），本代码提供的reinforce+G2ANet是否为GA-Common的实现呢？如果不是，那应该是哪个呢？多谢！

**Comment by starry-sky6688** [comment]
是GA-Common
