### ISSUE TITLE
关于attention的训练依据的问题

### ISSUE THREAD

**Issue by honey-mxy** [starry-sky6688/MARL-Algorithms#114]
作者您好！请问hard attention和softattention的训练依据是什么呢？好像没有找到对应的loss function，是和智能体强化学习共用目标吗？十分感谢！

**Comment by starry-sky6688** [comment]
g2anet只是一个网络，它需要配合reinforce或者central-v来进行训练，以central-v为例，更新g2anet的loss函数在这里：

https://github.com/starry-sky6688/MARL-Algorithms/blob/e9e32e122f1b25e1139b82bebbb7ed81dc1e2320/policy/central_v.py#L100
