### ISSUE TITLE
关于在别的环境应用qmix出现episodes rewards dropout的问题

### ISSUE THREAD

**Issue by ayton-zhang** [starry-sky6688/MARL-Algorithms#115]
作者您好，首先感谢您优质的开源项目，代码易读性很高，且迁移到其他的环境非常方便。

我将此算法迁移到了highway-env来完成我的项目，但是我始终遇到下面图片这个问题，就是算法先收敛到一个比较好的值，但是持续一会就下降并且震荡幅度很大。

我想问一下解决这个问题是提前停止训练（在已经有比较好的结果的时候）吗？我现在在使用默认的2000000步，您在SMAC中遇到过相关的问题吗？

下面两个图片是具体的情况，第二个是我用moving average处理过的。

![plot_episode_rewards](https://github.com/starry-sky6688/MARL-Algorithms/assets/63352175/c4fe6d9b-5672-4fb1-b5af-7df636ee4072)
![plot_ma_episode_rewards](https://github.com/starry-sky6688/MARL-Algorithms/assets/63352175/d32bad7a-a3b4-4c9f-8c12-f40376576de0)

**Comment by starry-sky6688** [comment]
正常的，off-policy算法不稳的，而且不同环境下的最优超参肯定也不一样；如果掉下来之前的reward已经达到你的预期，停止训练即可，否则就需要再调调参了

**Comment by Elapsedf** [comment]
> 作者您好，首先感谢您优质的开源项目，代码易读性很高，且迁移到其他的环境非常方便。
> 
> 我将此算法迁移到了highway-env来完成我的项目，但是我始终遇到下面图片这个问题，就是算法先收敛到一个比较好的值，但是持续一会就下降并且震荡幅度很大。
> 
> 我想问一下解决这个问题是提前停止训练（在已经有比较好的结果的时候）吗？我现在在使用默认的2000000步，您在SMAC中遇到过相关的问题吗？
> 
> 下面两个图片是具体的情况，第二个是我用moving average处理过的。
> 
> ![plot_episode_rewards](https://private-user-images.githubusercontent.com/63352175/337429685-c4fe6d9b-5672-4fb1-b5af-7df636ee4072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Nzk1NTksIm5iZiI6MTcyMDk3OTI1OSwicGF0aCI6Ii82MzM1MjE3NS8zMzc0Mjk2ODUtYzRmZTZkOWItNTY3Mi00ZmIxLWI1YWYtN2RmNjM2ZWU0MDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMTI1MjExOWNiNzFlNjViNWIyNzBmMGZlZmM5YjBiNDE2ZTRkNWExOWVmNzg1MzBlMDJkMjUzMmJhNzMzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2zgX5iSnp7DK_kfCghfA3ISBsFYxnKLBpz8_RS1SMGc) ![plot_ma_episode_rewards](https://private-user-images.githubusercontent.com/63352175/337429890-d32bad7a-a3b4-4c9f-8c12-f40376576de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Nzk1NTksIm5iZiI6MTcyMDk3OTI1OSwicGF0aCI6Ii82MzM1MjE3NS8zMzc0Mjk4OTAtZDMyYmFkN2EtYTNiNC00YzlmLThjMTItZjQwMzc2NTc2ZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmRlZjgzNGEyOGNjOTRmODcwNzkyMDg1YjhkMWQ1NGE1MTUyMDJkY2I5ZDBkZTY2OWVkMDdlNjNlYTExMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.APzYcP0jbS1yzTWT2eCocSfc6wEicN7lNOGHLKKjHzY)

您好，我目前也在尝试将Qmix应用到highway-env，方便请教下您用的highway-env是官方版本还是哪个版本呢~可以一起交流学习下~
