### ISSUE TITLE
关于get_action_weights的问题

### ISSUE THREAD

**Issue by honey-mxy** [starry-sky6688/MARL-Algorithms#117]
作者您好！请问在g2anet中，为什么将这里的weights是action的weights，即图中这里，我理解的是hard attention和soft attention融合后的attention，十分感谢作者的回答！
![微信图片_20240611125951](https://github.com/starry-sky6688/MARL-Algorithms/assets/171903764/f738521a-96e2-4286-9b28-4dcb3f776e68)

**Comment by starry-sky6688** [comment]
这个是agent在决策的时候输出的各个动作的权重，后续要根据 这个权重来为每个动作计算被采样的概率，再采样出一个动作来执行；hard attention和soft attention是模型内部的计算，这个已经是在模型外面了
