### ISSUE TITLE
您好，VDN和qmix为什么不能进行多智能体通信呢

### ISSUE THREAD

**Issue by lpplpf** [starry-sky6688/MARL-Algorithms#118]
您好，我没看懂您关于vdn和qmix不能通信的解释“vdn和qmix是直接根据Q值选动作的，没有办法进行通信。coma是AC方法，正好可以把commnet的结构用在actor上”，按说vdn和qmix虽然不是AC方法，但是critic网络同样可以通过通信来共享局部观察

**Comment by starry-sky6688** [comment]
本身方法就是这个形式，你根据自己的想法改进也是可以的

**Comment by lpplpf** [comment]
> 本身方法就是这个形式，你根据自己的想法改进也是可以的

收到，非常感谢
