### ISSUE TITLE
Questions about evaluation interval

### ISSUE THREAD

**Issue by ShengjieSun419** [starry-sky6688/MARL-Algorithms#121]
First of all, thank you for your excellent code.

Regarding the evaluation of the qmix, I have a question: Since the length of the episode of the sc2 environment is not fixed, the increase of `time_steps` after each sampling is unpredictable. As shown in the figure, the number of `steps` each time is likely to be different.
![image](https://github.com/user-attachments/assets/6e72e935-d928-4777-8eed-eb55dbaa10a7)

This means that as long as the change in `time_steps` is greater than `args.evaluate_cycle`, an evaluation can be performed. However, the `time_steps` when each evaluation is not necessarily an integer multiple of `args.evaluate_cycle`, as shown in figure.
![image](https://github.com/user-attachments/assets/d71ab7ea-f89d-4b2f-924e-89397af35d21)

So when drawing, does it mean that using an integer multiple of `evaluate_cycle` on the horizontal axis will introduce bias?
![image](https://github.com/user-attachments/assets/dae7a66f-df26-4e76-b069-10ded57648ed)

**Comment by starry-sky6688** [comment]
After each evaluation, `evaluate_steps` will be increased by one, and because `time_steps` is not a multiple of `args.evaluate_cycle`, we use `//` and `>` in https://github.com/starry-sky6688/MARL-Algorithms/blob/e9e32e122f1b25e1139b82bebbb7ed81dc1e2320/runner.py#L34C16-L34C71

**Comment by ShengjieSun419** [comment]
Hey, thanks for your reply.
Actually, my problem is the learning curve. The code [here](https://github.com/starry-sky6688/MARL-Algorithms/blob/e9e32e122f1b25e1139b82bebbb7ed81dc1e2320/runner.py#L84) specifies that the horizontal axis interval is `args.evaluate_cycle` when plotting. Strictly speaking, this is not correct, right? Because the evaluation interval is not strictly equal to `args.evaluate_cycle`. Moreover, in extreme cases, it may occur that the interval between two evaluations is greater than `2*args.evaluate_cycle`.

**Comment by starry-sky6688** [comment]
> Hey, thanks for your reply. Actually, my problem is the learning curve. The code [here](https://github.com/starry-sky6688/MARL-Algorithms/blob/e9e32e122f1b25e1139b82bebbb7ed81dc1e2320/runner.py#L84) specifies that the horizontal axis interval is `args.evaluate_cycle` when plotting. Strictly speaking, this is not correct, right? Because the evaluation interval is not strictly equal to `args.evaluate_cycle`. Moreover, in extreme cases, it may occur that the interval between two evaluations is greater than `2*args.evaluate_cycle`.

right

**Comment by ShengjieSun419** [comment]
> Hey, thanks for your reply. Actually, my problem is the learning curve. The code [here](https://github.com/starry-sky6688/MARL-Algorithms/blob/e9e32e122f1b25e1139b82bebbb7ed81dc1e2320/runner.py#L84) specifies that the horizontal axis interval is `args.evaluate_cycle` when plotting. Strictly speaking, this is not correct, right? Because the evaluation interval is not strictly equal to `args.evaluate_cycle`. Moreover, in extreme cases, it may occur that the interval between two evaluations is greater than `2*args.evaluate_cycle`.

Is there a way to avoid this problem and evaluate strictly at intervals of `args.evaluate_cycle` steps? This is actually important for fair comparisons when plotting. Looking forward to your reply.
