### ISSUE TITLE
为什么改名哇

### ISSUE THREAD

**Issue by 775269512** [starry-sky6688/MARL-Algorithms#89]
原仓库叫StarCraft，改名后无法检索，曾经引用过的论文和一些给审稿人的声明查找不到导致不必要的麻烦。
您的仓库对MARL社区有着巨大的影响力，如果可以的话，希望作者能保持原名，当然同时也尊重作者自身的意见。
谢谢您！

**Comment by starry-sky6688** [comment]
改名是因为这个项目库的核心毕竟是MARL算法，StartCraft只是一个应用的环境；另外后面也希望能找几个小伙伴一起把这个仓库继续维护下去，以算法为核心的角度出发，可能环境也会发生变化，所以给你们造成麻烦还请见谅呀~
