### ISSUE TITLE
关于QMIX的Trick：Eligibility traces

### ISSUE THREAD

**Issue by zanezhenli** [starry-sky6688/MARL-Algorithms#99]
作者你好。在阅读论文[Rethinking the Implementation Tricks and Monotonicity Constraint in Cooperative Multi-Agent Reinforcement Learning](https://arxiv.org/abs/2102.03479)后，想问下代码里有实现资格迹TD(λ)的部分吗？如果没有的话应该如何添加，能否给一个提示？

**Comment by starry-sky6688** [comment]
这个没有实现；添加的话在./policy/qmix.py里的learn()函数里添加，修改网络的更新方式
